### ISSUE TITLE
square mode

### ISSUE THREAD

**Issue by fishinstud** [TobiasLoader/Cylinder-Chess#22]
Hi again, is it intended for the king to be able to warp to the other side of the board in square mode? To reproduce this castle the king, move the opposite rook out of the corner square, move your king to the edge and on the following turn move the king to the opposite side of the board where a rook normally starts.

**Comment by TobiasLoader** [comment]
Hi, yes that is intended to happen, the king can wrap in the same way that every piece should be able to wrap (even pawns if they capture a piece on the edge of the board!). Playing on the square mode has the same rules as cylinder chess, you can think of the cylinder unfurling or flattening to become the square board. So in the same way as the king wraps from say the A to H file on the cylinder (eg. when you castle then move the king across), it will also wrap on the square.
Thanks for checking out the game fishinstud! If you have any other thoughts/suggestions/issues please post them :))
